//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using CapaDatos;
using System.Collections.Generic;

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoEmpleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PagoEmpleado()
        {
            this.PagoEmpleados = new HashSet<PagoEmpleado>();
        }

        public int ID_Empleado { get; set; }
        public System.DateTime fecha { get; set; }
        public double PagoHora { get; set; }
        public int CantHora { get; set; }
        public string TipoPago { get; set; }
        public double Total { get; set; }
    
        public virtual Empleado Empleado { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoEmpleado> PagoEmpleados { get; set; }
    }
}



//[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
//public Cliente()
//{
//    this.Pedidoes = new HashSet<Pedido>();
//}
//
//public int ID_cliente { get; set; }
//public string Nombre { get; set; }
//public string Apellido { get; set; }
//public int Edad { get; set; }
//public string Numero_telefono { get; set; }
//public string Correo_electronico { get; set; }
//public string Contrasenia { get; set; }
//public string Distrito { get; set; }
//
//[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
//public virtual ICollection<Pedido> Pedidoes { get; set; }
